### ISSUE TITLE
exifprobe endless loop

### ISSUE THREAD

**Issue by fgeek** [hfiguiere/exifprobe#11]
Input file: http://bugs.fi/media/afl/exifprobe/exifprobe-endless-loop.jpeg
SHA256: fd2e685b4f90f13bcb18fdb944ad6bf8d7e7ebc07a1301071ad2a29d694638d9
Command line: /home/hsalo/exifprobe/exifprobe -c exifprobe-endless-loop.jpeg

Output:
```
ERROR reading length of DHT
         because: Success
@0x0000002=2       :    <JPEG_DHT> FAILED to read unsigned short value at offset 4 (EOF)
```

**Comment by hfiguiere** [comment]
Fixed. Thank you so much for the report.
