### ISSUE TITLE
Consistent segmentation fault

### ISSUE THREAD

**Issue by jova2** [hfiguiere/exifprobe#15]
Hi,

As described at https://bugs.debian.org/874275

When running "exifprobe -L" I get consistent "segmentation fault". Same 
occurs without the -L option.

A backtrace is available in this bug.

I have packaged this current version to fix https://bugs.debian.org/809365 
and the submitter reported that the problem does not happen with the 
previous version.

Is not it time for a new release of exifprobe? :)

Thanks a lot!

**Comment by hfiguiere** [comment]
I can't reprodruce the crash with master as built in Fedora 28 x86_64, with the address sanitzer `-fsanitize=address`

**Comment by hfiguiere** [comment]
But with your downstream patch `https://salsa.debian.org/pkg-security-team/exifprobe/blob/debian/master/debian/patches/fix-makefile.patch`, it does.

**Comment by hfiguiere** [comment]
Should be fixed now.

The tl;dr strdup() prototype wasn't available causing it to be seen as returning an int. (sizeof int < sizeof void*)
