### ISSUE TITLE
Patches to add to the upstream code

### ISSUE THREAD

**Issue by jova2** [hfiguiere/exifprobe#16]
Hi again,

There are some patches in the exifprobe package in Debian that could be added to the upstream code.
https://salsa.debian.org/pkg-security-team/exifprobe/tree/debian/master/debian/patches
These are fixing compiler flags, hardening, spelling, and other fixes.
Please consider adding them to the main code.

Best Regards,

**Comment by hfiguiere** [comment]
One of these patches is causing issue #15.

**Comment by hfiguiere** [comment]
Took most of them. Off course I left out what's crashing.
