### ISSUE TITLE
denial of service with fuzzed sample file

### ISSUE THREAD

**Issue by fgeek** [hfiguiere/exifprobe#3]
Please see bug report https://bugs.debian.org/779527

**Comment by hfiguiere** [comment]
The debian bug report doesn't have the sample... (or it was mangled by the BTS)

**Comment by fgeek** [comment]
@hfiguiere Sorry about that. I have now resend it. I can also test patches after you have investigated these issues and do some more fuzzing. Please notify me in case you need more information or if I can help you somehow.

**Comment by hfiguiere** [comment]
Got it this time. Thanks.

**Comment by hfiguiere** [comment]
Fixed.
