### ISSUE TITLE
segfaults on invalid jpegs

### ISSUE THREAD

**Issue by jcowgill** [hfiguiere/exifprobe#5]
From:
https://bugs.debian.org/809365
https://lists.alioth.debian.org/pipermail/pkg-multimedia-maintainers/2015-December/049019.html

exifprobe segfaults when run on the two jpegs found in the above Debian bug report.

Stack traces:
https://gist.github.com/jcowgill/f26df00b90be21ab8d5f74b304054339

**Comment by hfiguiere** [comment]
This is fixed now. Thanks for your report, and sorry for the delays.
